# Generated by Django 4.1.6 on 2023-02-03 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_body', models.TextField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 0, 58, 753848, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
