# Generated by Django 4.1.6 on 2023-02-03 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
